apiVersion: v1
kind: Secret
metadata:
  name: "yelb-postgres-credentials"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  DBPASSWORD: {{ .Values.db.sql.password | quote }}
